apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::186911657558:user/github-actions
      username: github-actions
      groups:
        - system:masters
        
  mapRoles: |
    - rolearn: arn:aws:iam::186911657558:role/AWSEKSClusterRole
      username: AWSEKSClusterRole
      groups:
      - system:masters
    - rolearn: arn:aws:iam::186911657558:role/AWSEKSNodeRole
      username: AWSEKSNodeRole
      groups:
        - system:masters