name: Deploy docker container to EKS

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]


jobs:
  build:
    name: Deploy docker container to EKS
    runs-on: ubuntu-latest

    steps:
      - name: Check out code for building image
        uses: actions/checkout@v1

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
          

      - name: Update kube config
        run: aws eks update-kubeconfig --name ccet-ia-2 --region ap-south-1

      - name: Deploy image to Amazon EKS
        run: |
          kubectl apply -f eks/aws-auth.yaml
          kubectl apply -f eks/deployment.yaml
          kubectl apply -f eks/service.yaml
