name: Deploy docker container to EKS

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]


jobs:
  build:
    name: Deploy docker container to EKS
    runs-on: ubuntu-latest

    steps:
      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Update kube config
        run: aws eks update-kubeconfig --name ccet-ia-2 --region ap-south-1

      - name: Deploy image to Amazon EKS
        run: |
          kubectl get svc
